jobs:
  - job: cred_scan
    displayName: Credential Scan
    pool:
      vmImage: "windows-latest"
    steps:
      - task: CredScan@3
        displayName: 'Run CredScan'
        inputs:
          outputFormat: sarif
          debugMode: false
  - job: component_governance
    displayName: Component Governance
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: |
          pip install -U pip setuptools
          pip install -r requirements.txt
          pip freeze > requirements.txt
      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        displayName: 'Component Detection'