variables:
  skipComponentGovernanceDetection: true  # in case ADO Pipeline tries to inject it into every job, we only need to do this once which we do explicitly below
jobs:
  - job: cred_scan
    displayName: Credential Scan
    pool:
      vmImage: "windows-latest"
    steps:
      - task: CredScan@3
        displayName: 'Run CredScan'
        inputs:
          outputFormat: sarif
          debugMode: false
  - job: component_governance
    displayName: Component Governance
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: |
          pip install -U pip setuptools
          pip install -r requirements.txt
          pip freeze > requirements.txt
      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
        displayName: 'Component Detection'
  - job: build_documentation
    displayName: Build Documentation
    pool:
      - vmImage: "ubuntu-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: |
          pip install -U pip setuptools
          pip install -r requirements.txt
          sphinx-build -W -a docs/ docs/_build/html
  - job: code_fmt_check
    displayName: Code Format Validation
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: |
          pip install -U pip setuptools
          pip install black
          black --check --diff ./graspy ./tests
        displayName: "Code Format Validation"
  - job: mypy_type_check
    displayName: Type Check
    continueOnError: true  # soft addition of mypy for reporting purposes, shouldn't fail build -yet-
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: |
          pip install -U pip setuptools
          pip install mypy
          mypy -m graspy
        displayName: "Type Check"
  - job: test_coverage
    displayName: Test Coverage
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
      - script: |
          pip install -U pip setuptools
          pip install -r requirements.txt
          python -m pytest --co --cov=graspy
        displayName: "Test Coverage"
  - job: python_build
    displayName: Python Build
    strategy:
      matrix:
        linux_p36:
          os: "ubuntu-latest"
          python_version: "3.6"
        linux_p37:
          os: "ubuntu-latest"
          python_version: "3.7"
        linux_p38:
          os: "ubuntu-latest"
          python_version: "3.8"
        mac_p36:
          os: "macos-latest"
          python_version: "3.6"
        mac_p37:
          os: "macos-latest"
          python_version: "3.7"
        mac_p38:
          os: "macos-latest"
          python_version: "3.8"
        windows_p36:
          os: "windows-latest"
          python_version: "3.6"
        windows_p37:
          os: "windows-latest"
          python_version: "3.7"
        windows_p38:
          os: "windows-latest"
          python_version: "3.8"
    pool:
      vmImage: $(os)
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python_version)
      - script: |
          pip install -U pip setuptools
          pip install -r requirements.txt
          pytest tests
