name: graspologic Publish Release Notes
on:
  workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref=='refs/heads/main' || github.ref=='refs/heads/dev'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
          pip install -r requirements.txt
      - name: Create version environment variable
        run: |
          echo "GRASPOLOGIC_VERSION=`python setup.py --version`" >> $GITHUB_ENV
          echo "GRASPOLOGIC_TAG=v`python setup.py --version`" >> $GITHUB_ENV
      - name: Create release.rst file
        run: |
          python .github/scripts/build_release_notes.py
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Release Notes PR"
          git push
